---

# Version 1.0.0

- hosts: "localhost"
  gather_facts: true

  vars:
    dns_zone: "mydomain.com"
    dyndns_names:
      - "dyndns"
    api_key: ""
    external_ip_address: ""
    external_ipv6_address: ""
    ipv6_prefix: ""

    # DO NOT SET!
    dns_record_id: "" # Do not set!
    dns_record_type: "" # Do not set!

  tasks:
    - name: Assert that external IPv4 Address is set
      ansible.builtin.assert:
        that: "{{ external_ip_address | length > 0 }}"
        fail_msg: "It seems that you haven't provided an external IPv4 Address."
        success_msg: "IPv6 Address provided. Proceeding."

    - name: Assert that external IPv6 Address is set if no prefix was read
      when:
        - ipv6_prefix == ""
      ansible.builtin.assert:
        that: "{{ external_ipv6_address | length > 0 }}"
        fail_msg: "It seems that you haven't provided an external IPv6 Address."
        success_msg: "IPv6 Address provided. Proceeding."

    - name: Get Zone ID for {{ dns_zone }}
      ansible.builtin.uri:
        url: "https://api.hetzner.cloud/v1/zones?name={{ dns_zone }}"
        method: GET
        headers:
          Authorization: "Bearer {{ api_key }}"
      register: zone_id

    - name: Get all DNS Records for Zone {{ dns_zone }}
      ansible.builtin.uri:
        url: "https://api.hetzner.cloud/v1/zones/{{ zone_id.json.zones[0].id }}/rrsets"
        method: GET
        headers:
          Authorization: "Bearer {{ api_key }}"
      register: dns_records

#    - debug:
#        var: dns_records

    - name: Manage Record
      include_tasks: manage_record.yml
      loop: "{{ dyndns_names }}"
      loop_control:
        loop_var: dyndns_name
