---

- name: Manage DYNDNS Record
  block:
    - name: Initialize Variables
      set_fact:
        dns_a_record_id: ""
        dns_a_record_type: ""
        dns_a_record_value: ""
        dns_aaaa_record_id: ""
        dns_aaaa_record_type: ""
        dns_aaaa_record_value: ""

    - name: Lookup if DYNDNS A Record {{ dyndns_name }} exists in Zone {{ dns_zone }}
      set_fact:
        dns_a_record_id: "{{ item.id }}"
        dns_a_record_type: "{{ item.type }}"
        dns_a_record_value: "{{ item.records[0].value }}"
      when:
        - item.name == dyndns_name
        - item.type == "A"
      loop: "{{ dns_records.json.rrsets }}"

    - name: Lookup if DYNDNS AAAA Record {{ dyndns_name }} exists in Zone {{ dns_zone }}
      set_fact:
        dns_aaaa_record_id: "{{ item.id }}"
        dns_aaaa_record_type: "{{ item.type }}"
        dns_aaaa_record_value: "{{ item.records[0].value }}"
      when:
        - item.name == dyndns_name
        - item.type == "AAAA"
      loop: "{{ dns_records.json.rrsets }}"

#    - debug:
#        var: dns_a_record_id

    - name: DYNDNS A Record exist, will delete old entry
      when:
        - dns_a_record_id | length > 0
        - dns_a_record_value != external_ip_address
        - external_ip_address | length > 0
      ansible.builtin.uri:
        url: "https://api.hetzner.cloud/v1/zones/{{ zone_id.json.zones[0].id }}/rrsets/{{ dyndns_name }}/A"
        method: DELETE
        headers:
          Authorization: "Bearer {{ api_key }}"
        status_code: 201

    - name: DYNDNS A Record for {{ dyndns_name }} does NOT exist, will create it with external IPv4 as {{ external_ip_address }}
      when:
        - dns_a_record_id | length == 0
        - external_ip_address | length > 0
      ansible.builtin.uri:
        url: "https://api.hetzner.cloud/v1/zones/{{ zone_id.json.zones[0].id }}/rrsets"
        method: POST
        headers:
          Authorization: "Bearer {{ api_key }}"
        body_format: json
        body:
          name: "{{ dyndns_name }}"
          type: "A"
          records:
            - value: "{{ external_ip_address }}"
          ttl: 60
        status_code: 201

    - name: DYNDNS AAAA Record exist, will delete old entry
      when:
        - external_ipv6_address != ""
        - dns_aaaa_record_id | length > 0
        - dns_aaaa_record_value != external_ipv6_address
      ansible.builtin.uri:
        url: "https://api.hetzner.cloud/v1/zones/{{ zone_id.json.zones[0].id }}/rrsets/{{ dyndns_name }}/AAAA"
        method: DELETE
        headers:
          Authorization: "Bearer {{ api_key }}"
        status_code: 201

    - name: DYNDNS AAAA Record for {{ dyndns_name }} does NOT exist, will create it with external IPv6 as {{ external_ipv6_address }}
      when:
        - dns_aaaa_record_id | length == 0
        - external_ipv6_address | length > 0
      ansible.builtin.uri:
        url: "https://api.hetzner.cloud/v1/zones/{{ zone_id.json.zones[0].id }}/rrsets"
        method: POST
        headers:
          Authorization: "Bearer {{ api_key }}"
        body_format: json
        body:
          name: "{{ dyndns_name }}"
          type: "AAAA"
          records:
            - value: "{{ external_ipv6_address }}"
          ttl: 60
        status_code: 201

  rescue:
    - name: There was an error
      debug:
        msg: "There was an Error DNS name {{ dyndns_name }} registration. Proceed with next entry!"
